//! The `x-ratatoskr-provenance` header and the provenance-free `source_digest`.
//!
//! `ARCHITECTURE.md` S11 requires generated outputs to carry a provenance header with generator
//! version, source digest and contract version. JSON Schema has no comment syntax, so the header
//! is a top-level extension keyword. It sorts last under `x`, which keeps the readable part of
//! the file at the top.

use sha2::Digest as _;

/// The top-level extension keyword holding the provenance block.
pub const PROVENANCE_KEY: &str = "x-ratatoskr-provenance";

/// The generated-file marker `AGENTS.md` requires on every generated artifact.
pub const GENERATED_MARKER: &str = "DO NOT EDIT — generated by contractsc from the canonical \
                                    Rust source. Change the Rust type and run \
                                    `cargo contracts generate`.";

/// The standing warning that the published schema is a lower bound on validity.
pub const VALIDATION_NOTE: &str = "This schema is a LOWER BOUND on validity. Cross-field \
                                   invariants and canonical-form rules are enforced by the \
                                   canonical Rust type; see fixtures/invalid-expectations.toml \
                                   for which layer rejects what.";

/// The name recorded as the producing generator.
pub const GENERATOR_NAME: &str = "contractsc";

/// The schemars version this build was compiled against.
///
/// schemars shapes the bytes, so the recorded identity must be true: test `P-4` cross-checks this
/// constant against `Cargo.lock`.
pub const SCHEMARS_VERSION: &str = "1.2.2";

/// `sha256:<64 lowercase hex>` over the rendered schema **with the provenance member absent**.
///
/// This is the digest definition. It is a pure function of contract shape, is not
/// self-referential, and is recomputable by anyone holding the file: delete
/// `x-ratatoskr-provenance`, re-render with the canonical serializer, hash. Test `P-2` does
/// exactly that.
#[must_use]
pub fn source_digest(provenance_free_body: &str) -> String {
    format!(
        "sha256:{}",
        hex::encode(sha2::Sha256::digest(provenance_free_body.as_bytes()))
    )
}

/// Recomputes the `source_digest` a generated file's own body implies.
///
/// Strips `x-ratatoskr-provenance`, re-renders with the canonical serializer and hashes. A
/// mismatch against the embedded digest means the file was **edited by hand**, which is why
/// `check` reports it as `Tampered` rather than as routine staleness.
///
/// # Errors
///
/// Returns the parse error text when `body` is not a JSON Schema document.
pub fn recompute_digest(body: &str) -> Result<String, String> {
    let mut schema: schemars::Schema =
        serde_json::from_str(body).map_err(|error| error.to_string())?;
    schema.remove(PROVENANCE_KEY);
    Ok(source_digest(&crate::render::render(&schema)))
}

/// The embedded `source_digest` of a generated file, if it has one.
#[must_use]
pub fn embedded_digest(body: &str) -> Option<String> {
    let parsed: serde_json::Value = serde_json::from_str(body).ok()?;
    parsed
        .get(PROVENANCE_KEY)?
        .get("source_digest")?
        .as_str()
        .map(str::to_owned)
}

/// Builds the nine-member provenance block.
///
/// There is deliberately **no** `generated_at`: a timestamp is the single most common cause of a
/// generator that cannot reproduce its own output.
#[must_use]
pub fn block(
    canonical_source: &str,
    contract_id: &str,
    contract_major_version: u32,
    generator_version: &str,
    source_digest: &str,
) -> serde_json::Value {
    serde_json::json!({
        "canonical_source": canonical_source,
        "contract_id": contract_id,
        "contract_major_version": contract_major_version,
        "generated": GENERATED_MARKER,
        "generator": GENERATOR_NAME,
        "generator_version": generator_version,
        "schemars_version": SCHEMARS_VERSION,
        "source_digest": source_digest,
        "validation_note": VALIDATION_NOTE,
    })
}
