//! The schema generator settings and the one canonical serializer for generated artifacts.
//!
//! Every generated byte in this repository leaves through [`render`]. Two-space pretty printing,
//! exactly one trailing `\n`, UTF-8, no BOM — the same rule
//! [`ratatoskr_identifiers::canonical_json`] applies to fixtures.

/// A fresh generator configured for the published contract.
///
/// `for_deserialize` is deliberate: the published schema is the **validation** contract, so it
/// describes what a consumer must accept, not what this build happens to emit. Test `P-5` asserts
/// that the serialize and deserialize contracts currently produce identical bytes; if that ever
/// stops being true, both must be published.
#[must_use]
pub fn generator() -> schemars::SchemaGenerator {
    schemars::generate::SchemaSettings::draft2020_12()
        .for_deserialize()
        .into_generator()
}

/// The one canonical serializer for generated artifacts.
///
/// `schemars::Schema` has a custom `Serialize` that emits a fixed keyword order
/// (`$id, $schema, title, description, type, format, properties`, then the remaining keys
/// lexicographically, then `$defs`), and `serde_json::Map` is a `BTreeMap` unless
/// `preserve_order` is enabled, so the byte order of the result does not depend on the order in
/// which members were inserted.
///
/// # Panics
///
/// Never in practice. A [`schemars::Schema`] wraps a [`serde_json::Value`], whose serialization
/// is infallible; a failure here would mean a broken build rather than a contract problem.
#[must_use]
#[allow(
    clippy::expect_used,
    reason = "a schemars::Schema wraps a serde_json::Value, which is infallibly serializable; a \
              failure here is a broken build, not a contract problem"
)]
pub fn render(schema: &schemars::Schema) -> String {
    let mut rendered =
        serde_json::to_string_pretty(schema).expect("a Schema is always serializable");
    rendered.push('\n');
    rendered
}
